### ISSUE TITLE
Check, why mobile score is marked as passed then scored below 80 points

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Performance#16]

**Comment by linasmatakas** [comment]
chart's score background are defined by CSS, desktop is set to 80 and mobile is set to 60 at the moment.

**Comment by VaclovasV** [comment]
why we have 60 on mobile?

**Comment by linasmatakas** [comment]
There is no particular reason for 60, but I think that we will have different pass scores for mobile and desktop.

**Comment by VaclovasV** [comment]
Google, not us decides, then score is "passed".
Just replicate "passing" score value from google.
