### ISSUE TITLE
Add visual benchmark to page insights sections 

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Performance#24]
![screenshot at jun 25 14-31-17](https://cloud.githubusercontent.com/assets/10126531/8353468/e0cd8eb6-1b46-11e5-9df3-38ac1008c753.png)

Also, we should have ability to set benchmark manually via config file

**Comment by JuliusSenkus** [comment]
For Linas, use firstCtrl.MinimumPassScore to add visual benchmark.
