### ISSUE TITLE
"Failed to get speed test data!" error

### ISSUE THREAD

**Issue by onurdegerli** [devbridge/Performance#45]
Hi,

1. I install the npm module with this command: 
npm install devbridge-perf-tool --save-dev -f

2. I clone the repo.

3. I remove the comment out in these lines:
gulp.task('perf-tool', function(){
    performance({
        siteURL:"https://www.google.com",
        sitePages: ["/", "/voice"],
        runDevPerf:true,
        runHtmlTest:true,
        runGoogleSpeedTest:true
    });
});

gulp.task('default', ['perf-tool']);
 
4. I run the project with this url: http://localhost/performance I get this error:
"Failed to get speed test data!" error

What should I do to run correctly?

**Comment by VaclovasV** [comment]
@onurdegerli - after you run gulp, does it successfully finishes task?

**Comment by onurdegerli** [comment]
I install the gulp with this: npm install gulp -g
than
$ gulp
and I get this output:

[12:56:09] Using gulpfile /var/www/performance/gulpfile.js
[12:56:09] Starting 'perf-tool'...
Running "customdevperf" task

Running "devperf" task

Running "phantomas:httpswwwgooglecom" (phantomas) task
(Google page speed) Job started.
[12:56:10] Finished 'perf-tool' after 301 ms
[12:56:10] Starting 'default'...
[12:56:10] Finished 'default' after 23 μs
(Google page speed) Done 1 out of 4
(Google page speed) Done 2 out of 4
(Google page speed) Done 3 out of 4
(Google page speed) Done 4 out of 4
(Google page speed) Job finished! Writing results.
(Html test) Done 1 out of 2
(Html test) Done 2 out of 2
(Html test) Writing results...
(Html test) Job completed.

Running "phantomas:httpswwwgooglecomvoice" (phantomas) task

Running "devperfAfter" task
Looking for result files in ./node_modules/devbridge-perf-tool/devperf/httpswwwgooglecom/data
Looking for result files in ./node_modules/devbridge-perf-tool/devperf/httpswwwgooglecomvoice/data
File "./node_modules/devbridge-perf-tool/devperf/results.json" created.
File "./node_modules/devbridge-perf-tool/devperf/settings.json" created.
Assets copied.

Running "anonymous_task" task

**Comment by VaclovasV** [comment]
and after this, results are not displayed? Do you get any generated file after task is complete?

**Comment by onurdegerli** [comment]
yes, results are not displayed.
where is the place which the file generated?
did you mean this directory? /node_modules/devbridge-perf-tool/devperf/*.json?

**Comment by onurdegerli** [comment]
I also get this error from console.
SpeedTestViewApp.js:61 GET http://localhost/performance/settings.txt?1468329706051 404 (Not Found)

**Comment by VaclovasV** [comment]
I think, default path is /perf-tool, not /performance
I went through all process from zero, installed package, runed task and everything went ok.
Tool generated setings.txt and speedtest.txt inside perf-tool directory (this directory is found in the project root or where node_modules are found).

**Comment by VaclovasV** [comment]
Do you have these generated?
http://prntscr.com/bry5pt

**Comment by onurdegerli** [comment]
Ok, I see.
There is another generated perf-tool directory in my web performance directory.
Thanks a lot.

By the way, is my installation process correct?
1 - npm install devbridge-perf-tool --save-dev -f
2 - Clone repo.
3 - Install gulp.
4 - Run gulp.

**Comment by VaclovasV** [comment]
You don't need to clone repo :) Tool installs after npm install devbridge-perf-tool command and you are able to use it in project directory.
I will close this, as issue is resolved, feel free to reopen if you will have other issues.
